const data = {
    "count": 105440343,
    "results": [
    {
    "listing_id": 786913543,
    "user_id": 176554548,
    "shop_id": 19270059,
    "title": "Birthday svg – Nutrition facts svg – Nutrition svg – Birthday facts clipart – Birthday party label svg – eps, png, dxf pdf, svg for cricut",
    "description": "BIRTHDAY NUTRITION FACTS 📝designs for cricut, silhouette, cameo to decorate t-shirts, mugs and others\n\n\n---------------\nINCLUDE\n\n2 SVG files – for die cut software like Cricut  ✂️      \n2 EPS files – for graphic software like Illustrator  🎨 \n2 PNG files – for web graphics  🖥\n2 DXF – for Silhouette basic  🛠\n2 PDF – for printing  🖨\n\n\n---------------\nINSTANT DOWNLOAD\n\nYou can download the files directly from your Etsy account in seconds after the purchase.\n\n\n---------------\nPERSONAL AND SMALL COMMERCIAL USE\n\nYou can produce and sell 30 physical items with my design.\nIf you need to make more, you should renew the license by purchasing the design again for the next 30 items.\n\n\n---------------\nTHANK YOU FOR VISITING!\n\n\n\n\n\nReselling, sharing or redistributing is not allowed.",
    "state": "active",
    "creation_timestamp": 1653422078,
    "created_timestamp": 1653422078,
    "ending_timestamp": 1664049278,
    "original_creation_timestamp": 1584275563,
    "last_modified_timestamp": 1653422078,
    "updated_timestamp": 1653422078,
    "state_timestamp": 1647033853,
    "quantity": 47,
    "shop_section_id": 33169679,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/786913543/birthday-svg-nutrition-facts-svg",
    "num_favorers": 398,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "download",
    "tags": [
    "die cut",
    "nutrition facts svg",
    "nutrition svg",
    "nutritional svg",
    "facts label svg",
    "nutrition png",
    "nutrition clipart",
    "birthday svg",
    "birthday nutrition",
    "birthday facts svg",
    "birthday party svg",
    "birthday clipart",
    "birthday label svg"
    ],
    "materials": [],
    "shipping_profile_id": null,
    "processing_min": null,
    "processing_max": null,
    "who_made": "i_did",
    "when_made": "2020_2022",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "1 ZIP",
    "has_variations": false,
    "should_auto_renew": false,
    "language": "en-US",
    "price": {
    "amount": 189,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 6844,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 633285555,
    "user_id": 124648166,
    "shop_id": 16300691,
    "title": "Wine glasses with engraving as a wedding gift – Personalized wine glasses – Gifts for couples – Red wine – 2 hearts",
    "description": "For many people, the wedding is one of the most beautiful days in life. For this special occasion, of course, you also need beautiful and unusual gift ideas. Personalized red wine glasses fit perfectly into this scheme. Above all, wedding couples will remember this beautiful day with such a gift long after the wedding day. The engraving makes the red wine glasses look very noble, and thus they enrich every showcase in the living room. With these beautiful engraved red wine glasses, the wedding couple can continue to toast on any anniversary in the future and revel in romantic memories.\n\nThese red wine glasses from Leonardo, engraved using state-of-the-art laser technology, are perfect as a gift for very special people. Or make yourself an unmistakable gift. Either way, these personalized red wine glasses make drinking even more fun. Two noble glasses for noble drops.\n\n- Volume: 460 ml\n- Height: 23 cm\n- Diameter: 8.5 cm\n- Engraving color: milky / white\n- Dishwasher safe\n- Glass quality from Leonardo",
    "state": "active",
    "creation_timestamp": 1653422076,
    "created_timestamp": 1653422076,
    "ending_timestamp": 1664049276,
    "original_creation_timestamp": 1533207096,
    "last_modified_timestamp": 1653422076,
    "updated_timestamp": 1653422076,
    "state_timestamp": 1650566832,
    "quantity": 78,
    "shop_section_id": 23379237,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/633285555/wine-glasses-with-engraving-as-a-wedding",
    "num_favorers": 81,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": true,
    "personalization_is_required": true,
    "personalization_char_count_max": 256,
    "personalization_instructions": "Für Ihre persönlichen Rotweingläser benötigen wir folgende Angaben von Ihnen, die Sie uns ganz leicht über das Bestellfeld mitteilen können:\n-Die gewünschten Namen\n-Das gewünschte Datum",
    "listing_type": "physical",
    "tags": [
    "wine glasses",
    "red wine glasses",
    "wine glasses with engraving",
    "personalized wine glasses",
    "gifts for couples",
    "couple gifts",
    "wedding presents",
    "wedding gift ideas",
    "gifts for the wedding",
    "valentine&#39;s day gift",
    "gifts for Valentine&#39;s Day",
    "anniversary gift",
    "Easter gifts"
    ],
    "materials": [],
    "shipping_profile_id": 59300933478,
    "processing_min": 1,
    "processing_max": 2,
    "who_made": "i_did",
    "when_made": "made_to_order",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": false,
    "should_auto_renew": true,
    "language": "MACHINE_en",
    "price": {
    "amount": 2095,
    "divisor": 100,
    "currency_code": "EUR"
    },
    "taxonomy_id": 1667,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 581247978,
    "user_id": 53602806,
    "shop_id": 10115837,
    "title": "Legend and Legacy Matching Shirts, Father and Son, Father and Daughter, Daddy and Me Shirts",
    "description": "**Order Instructions**\n\nSelect each shirt separately. In the DROPDOWN MENU, select Legend Shirt(s) and Legacy Shirt(s). These are SOLD SEPARATELY due to the varying sizes and quantities needed. \n\n** THESE ARE NOT CUSTOMIZABLE **\n\n\nEvery father wants to leave a legacy for his children. These Legend and Legacy shirts are another modern take on the special bond between fathers and their children. \n\n\nLegend  (Adult)\n\n- Standard Men&#39;s Sizing: Small, Medium, Large, X-Large, 2 XL, 3XL\n- Color: Black\n- Type: Distressed Neck and Sleeve, Round Neck Tee\n- Screen Printed\n\nLegacy:\n\n- Sizing: 3-6 months, 9-12 months, 18-24,  2-4 years (Small), 6-8 years (Medium), 10-12 years (Large)\n- Color: Black\n- Type: Distressed Neck and Sleeve, Round Neck Tee\n- Screen Printed\n\n_______________________________________________________________________________________________\n\n\n***Join our email list for 10% OFF COUPON on your first purchase!***\n\nhttps://mailchi.mp/tolittlearrows/jointhetribe\n\n_______________________________________________________________________________________________\n\n\nALSO IN OUR SHOP:\nMatching Father and Son Hats & Tees: \nhttps://www.etsy.com/shop/tolittlearrows?ref=seller-platform-mcnav&section_id=19140614\n\nMatching Mommy and Me Wear: \nhttps://www.etsy.com/shop/tolittlearrows?ref=seller-platform-mcnav&section_id=18568294\n\nMom Hats:\nhttps://www.etsy.com/shop/tolittlearrows?ref=seller-platform-mcnav&section_id=22977958\n\nMom Dresses and Shirts: \nhttps://www.etsy.com/shop/tolittlearrows?ref=seller-platform-mcnav&section_id=18572903\n\nMaternity Tops: \nhttps://www.etsy.com/shop/tolittlearrows?section_id=18572895\n\n_______________________________________________________________________________________________\n\n\n© Copyright to: little arrows, 2016: All images, designs, and text are copyrighted and cannot be stored, reproduced, or used without obtaining prior written consent from the owner.\n\n© Copyright to: little arrows, 2016: All images, designs, and text are copyrighted and cannot be stored, reproduced, or used without obtaining prior written consent from the owner.",
    "state": "active",
    "creation_timestamp": 1653422075,
    "created_timestamp": 1653422075,
    "ending_timestamp": 1664049275,
    "original_creation_timestamp": 1519087167,
    "last_modified_timestamp": 1653422075,
    "updated_timestamp": 1653422075,
    "state_timestamp": 1639425944,
    "quantity": 780,
    "shop_section_id": 19140614,
    "featured_rank": 32,
    "url": "https://www.etsy.com/listing/581247978/legend-and-legacy-matching-shirts-father",
    "num_favorers": 1088,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
    "father gift",
    "gift for men",
    "Legend and Legacy",
    "Father and Son",
    "Daddy and Me Shirts",
    "Dad and Son Matching",
    "Father Son Matching",
    "Father Daughter",
    "Comfortable"
    ],
    "materials": [
    "son hat",
    "dad hat",
    "kids hat",
    "SnapBack hat",
    "Flexfit hat"
    ],
    "shipping_profile_id": 18354796957,
    "processing_min": 3,
    "processing_max": 5,
    "who_made": "i_did",
    "when_made": "made_to_order",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": true,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 2200,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 11110,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 1073891237,
    "user_id": 102986938,
    "shop_id": 14550861,
    "title": "Personalized Boho Rainbow Birthday Girl Rose Gold Tutu Bloomers Outfit, Vintage Rose Onesie®, Blush Pink One Ruffle, Outfit Cake Smash",
    "description": "♥ Personalized Boho Rainbow Tutu Bloomers Set ♥\n\nThis sweet outfit is sure to be a special addition to your little one&#39;s wardrobe. It&#39;s perfect for cake smash photos! This bloomers are soft and fluffy! Bodysuit has 3 snap closure. The headband is soft and stretchy. Your choice of a flutter sleeve bodysuit, Gerber Onesie®, or Carter&#39;s Bodysuit.\n\n\n:::::::::::::::::::::::::\n♥Outfit Details♥\n:::::::::::::::::::::::::\nBodysuit: 100% Cotton, 3 button snap closure. Expandable shoulders (flutter sleeve option does not have expandable shoulders).\n\nTutu Bloomers: Vintage Pink. Soft chiffon layers all around, matching satin bow on the back. Elastic waistband. \n\nHeadband: Soft and stretchy oversized bow design.\n\nI make these shirts using a professional textile printer and commercial heat press equipment. Made to last, wear after adorable wear:) The design in dyed right into the fabric so it&#39;s very soft to the touch and extremely durable with no special washing instructions :)\n\n\n:::::::::::::::::::::::::::::::\nHAVE A QUESTION?\n:::::::::::::::::::::::::::::::\nSend me a message, I do my best to respond right away during business hours!\n\n:::::::::::::::::::::::::::::::::::::::\nSHIPPING INFORMATION\n:::::::::::::::::::::::::::::::::::::::\nMy processing times change based on availability. To see my current processing time please see the &quot;READY TO SHIP IN&quot; timeline shown at the top of the listing. That information is always kept up to date. The &quot;ready to ship&quot; time is the time it takes to make the order and is in addition to the delivery time. Once shipped, delivery typically takes 5-10 business days within Canada and to the United States. International shipping takes 2-4 weeks. Leaving a date in the notes during checkout does not speed up the times stated above.\n\n:::::::::::::::::::::::::::::\nORDER TRACKING\n:::::::::::::::::::::::::::::\nThe free shipping option for this item does not offer tracking. If that is a feature you require you can use the link below to upgrade your shipping to a method that includes tracking:\n\n\nhttps://www.etsy.com/ca/listing/850711573/add-tracking\n\n:::::::::::::::::::::::\nRUSH ORDERS\n:::::::::::::::::::::::\nIf you need your order faster than the timeline outlined in the SHIPPING INFORMATION section above, please contact me BEFORE ordering. \n\nThank you for choosing Songbird Celebrations!\nJaime",
    "state": "active",
    "creation_timestamp": 1653422075,
    "created_timestamp": 1653422075,
    "ending_timestamp": 1664049275,
    "original_creation_timestamp": 1629918975,
    "last_modified_timestamp": 1653422075,
    "updated_timestamp": 1653422075,
    "state_timestamp": 1651331849,
    "quantity": 961,
    "shop_section_id": 21419117,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/1073891237/personalized-boho-rainbow-birthday-girl",
    "num_favorers": 285,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": true,
    "is_personalizable": true,
    "personalization_is_required": false,
    "personalization_char_count_max": 256,
    "personalization_instructions": "If ordering the top please enter the name that you would like used here:",
    "listing_type": "physical",
    "tags": [
    "bloomers headband",
    "pink and gold",
    "blush pink",
    "rainbow birthday",
    "rainbow party",
    "baby rainbow",
    "rainbow outfit",
    "neutral colors baby",
    "first birthday",
    "1st birthday rainbow",
    "cake smash photos",
    "cake smash party",
    "mauve baby girl"
    ],
    "materials": [],
    "shipping_profile_id": 116587186609,
    "processing_min": 1,
    "processing_max": 1,
    "who_made": "i_did",
    "when_made": "made_to_order",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": true,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 3499,
    "divisor": 100,
    "currency_code": "CAD"
    },
    "taxonomy_id": 2189,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 899443951,
    "user_id": 250251532,
    "shop_id": 21611596,
    "title": "Basketball Gift Box, Basketball Player Letterbox Gift, Bball Pampering Box Gift, Basketball Present, Basketball Lockdown Quarantine Gift,",
    "description": "Our “Basketball Kit” is here if you are looking for a birthday present or a little pick me up for any basketball player. \n\nIt comes with 6 uplifting items, guaranteed to put a smile on the recipient.\n\n1- Pencil Bag - \n   Eat. \n   Sleep. \n   Basketball \n   Repeat.\n2- Basketball Keyring\n3- Basketball Socks\n4- Black & Green Chocolates x 2\n5- Chocolate Hearts x 2 \n6- Under Eye Mask \n\nAnd as always we have a number of heartfelt and thoughtful gifts full of relaxing treats, so please check out our Store to see all of the pampering and care packages available. \n\nWe are also able to create customs letterbox hampers so please ask, if we hold the stock we will accommodate.\n\nThese letterbox gifts (size is 222 x 160 x 20mm) cleverly fit through the letterbox so they can be delivered if no one’s in.\n\nPlease choose from the “Card Type” list. If you can’t find a suitable card type for the situation please let us and we will try to accommodate.\n\nSimply add your personal message and we’ll do the rest!\n\nIf we do not receive a message the card will be placed blank inside :)\n\nIn the rare occasion we run out of stock of any product, we will always replace it for a similar product of the same value. \n\nIf you have any allergy concerns, please see each item individually for further information.\n\nThis kit is dispatched with Royal Mail 2nd Class and delivery is included in the price; Royal Mail states this option takes 3 to 5 working days, but please be aware this is not guaranteed. Please note there is no tracking option with this delivery service. \n\nPLEASE READ:\n\nWe are able to drop off your kit in our local post box in 1 working day after your order is placed; this is a standard service and the tracking option isn’t available.\n\nGiven the current events with COVID 19 please expect some delays. Royal Mail will only look into missing parcels 10 working days after the due date.\n\nWith that in mind, the Royal Mail are extremely reliable and I never had a missing order.\n\nThank you for your visit.\n\nDC Kits",
    "state": "active",
    "creation_timestamp": 1653422074,
    "created_timestamp": 1653422074,
    "ending_timestamp": 1664049274,
    "original_creation_timestamp": 1604665008,
    "last_modified_timestamp": 1653422074,
    "updated_timestamp": 1653422074,
    "state_timestamp": 1651065699,
    "quantity": 2,
    "shop_section_id": null,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/899443951/basketball-gift-box-basketball-player",
    "num_favorers": 7,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
    "basketball present",
    "sports gift",
    "basketball gift",
    "basketball player",
    "self-care gift",
    "pamper box",
    "you got this gift",
    "pampering box",
    "letter box sized",
    "hug in a box",
    "pampering hamper",
    "pampering gift",
    "care package"
    ],
    "materials": [],
    "shipping_profile_id": 86175966017,
    "processing_min": 1,
    "processing_max": 1,
    "who_made": "i_did",
    "when_made": "2020_2022",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": true,
    "should_auto_renew": false,
    "language": "en-US",
    "price": {
    "amount": 1299,
    "divisor": 100,
    "currency_code": "GBP"
    },
    "taxonomy_id": 322,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 1232044783,
    "user_id": 165624916,
    "shop_id": 18276207,
    "title": "Disneyy Trip 2022 SVG and PNG, Family Trip SVG, DisneyWorld Shirts Svg, DisneyLand Shirts Png, Cricut Ready, Instant Download!",
    "description": "*** These files are not compatible with Adobe. Please do not purchase these files for Adobe. Thank you!\n\nDisneyy Family Trip 2022 Mickey and Minnie Mouse Head with Castle. Cricut ready files. Instant Download!\n\n**Not to be resold as digital files. OK for small business and commercial use.\n\n*Colored watermark background does not show in downloads. The image is black & white\nUse to create your own family Shirts, bags, hats, cups and so much more!!\n\nThis is a digital download that will include 1 of each of the following: 2 SVG&#39;s, 2 PNG&#39;s. Nothing physical will be shipped!\n\nOnce your payment has been approved you will be able to download your files immediately.\n\nPlease make sure your system is compatible with the file type before purchase.\n\nI do not except returns but please message me if you need help with your downloads. I am happy to help!\n\nThank you so much for supporting my small business!\n\nHappy Crafting! :)",
    "state": "active",
    "creation_timestamp": 1653422070,
    "created_timestamp": 1653422070,
    "ending_timestamp": 1664049270,
    "original_creation_timestamp": 1652377757,
    "last_modified_timestamp": 1653422070,
    "updated_timestamp": 1653422070,
    "state_timestamp": 1652377758,
    "quantity": 990,
    "shop_section_id": 37954303,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/1232044783/disneyy-trip-2022-svg-and-png-family",
    "num_favorers": 13,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "download",
    "tags": [
    "DisneyWorld",
    "shirts",
    "family",
    "vacation",
    "2022",
    "svg",
    "png",
    "mickey",
    "minnie",
    "mouse",
    "cricut",
    "trip",
    "disney"
    ],
    "materials": [],
    "shipping_profile_id": null,
    "processing_min": null,
    "processing_max": null,
    "who_made": "i_did",
    "when_made": "2020_2022",
    "is_supply": true,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "2 PNG, 2 other files",
    "has_variations": false,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 200,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 6844,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 1030770829,
    "user_id": 112433298,
    "shop_id": 17173912,
    "title": "Pastel blooms Botanical embroidery pattern",
    "description": "Pastel blooms Botanical embroidery pattern\n\nNew in our Botanical Collection of embroidery panels is this wonderful pale floral design featuring ranunculus style and springlike flowers in soft and muted colours. The Pastel Blooms panel shows again Annie&#39;s colour sensitivity with a calming and restricted colour palette.\n\nWe are really pleased to offer you our collection of gorgeous hand painted illustrations which are digitally pre-printed onto luxurious cotton/linen panels with eco friendly inks. These panels are more than standard embroidery patterns with the artwork pre-printed, so no need for transferring designs. They are suitable for beginners along with more experienced embroiderers, for use with hand embroidery, freemotion embroidery, applique or even needle felting embellishment. Simply stitch as much or as little as you desire! Ideal starting points for those crafters who are unsure of their own illustrations but want a helping hand and something more modern. We have designed them to fit a 6 inch hoop or 6 inch aperture mount, with the actual Linen being approximately 25cm square. Now available in addition to our collection of gift boxed sets so that crafters and sewing enthusiasts who already possess the necessary equipment also have access to our designs. Please be advised that these printed designs do not come with any instructions. If you would prefer to have instructions and stitch guides, then our boxed kits include everything you need to while away some blissful relaxing hours creating some modern embroidery hoop art, from the linen, threads, needles and felt for the backing! These pre-printed embroidery panels could be developed into cushions, bags or simply framed as your very own piece of art. It is amazing to see the designs come to life with the addition of stitching. We present these embroidery patterns in a cellophane wrap ensuring they arrive with you clean and pristine! A perfect portable craft!\n\nThe linen pattern is around 25cm square, fitting a 6 inch hoop or 6 inch aperture mount.\n\n\nhttps://www.etsy.com/uk/shop/AnniemEmbroidery?ref=search_shop_redirect\n\n**Please Note** \nAll our designs, Panels and kits are purely for your enjoyment only and are not be used or resold for any commercial purpose.\n\nFor those of you that don&#39;t have any embroidery supplies, we do also offer a range of complete kits. They include everything you need to complete your finished piece..… Full colour printed image on luxury linen mix fabric, Stitch map, threads, needles 6” elbessee wooden hoop, backing for your piece,  and a stitch guide.\n You can find our kits here:-\nhttps://www.etsy.com/shop/AnniemEmbroidery?section_id=33777658\n \nhttps://www.etsy.com/shop/AnniemEmbroidery?section_id=33793251\n\n\nNeed a hoop, threads, needles??\nYou can find a range of  Embroidery essentials in our ‘EMBROIDERY SUPPLIES’ section here:-  \n \nhttps://www.etsy.com/shop/AnniemEmbroidery?section_id=33295214\n",
    "state": "active",
    "creation_timestamp": 1653422069,
    "created_timestamp": 1653422069,
    "ending_timestamp": 1664049269,
    "original_creation_timestamp": 1622804315,
    "last_modified_timestamp": 1653422069,
    "updated_timestamp": 1653422069,
    "state_timestamp": 1648060164,
    "quantity": 13,
    "shop_section_id": 23910141,
    "featured_rank": 2,
    "url": "https://www.etsy.com/listing/1030770829/pastel-blooms-botanical-embroidery",
    "num_favorers": 69,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
    "Embroidery Pattern",
    "modern embroidery",
    "pre printed pattern",
    "diy craft kit",
    "embroidery design",
    "flowers embroidery",
    "beginner embroidery",
    "simple needlework",
    "pre printed fabric",
    "DIY hoop art",
    "Embroidery panel",
    "Crewel pattern",
    "Pastel blooms"
    ],
    "materials": [],
    "shipping_profile_id": 104062729456,
    "processing_min": 1,
    "processing_max": 2,
    "who_made": "i_did",
    "when_made": "2020_2022",
    "is_supply": true,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": false,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 800,
    "divisor": 100,
    "currency_code": "GBP"
    },
    "taxonomy_id": 6346,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 855452154,
    "user_id": 84526176,
    "shop_id": 12778643,
    "title": "Off White Ombre Fairy Dust  by V and Co Vanessa Christenson for Moda fabrics.ombre w/ metallic dot 10871 332M.Sold in HALF yard increments",
    "description": "This listing is for 1 Cut of Moda fabric\n\nOmbre Fairy Dust Off White\n10871 332M Moda Metallic\nManufacturer:Moda\n\nManufacturer Item:10871 332M\nDescription:100% Cotton\nType:44&quot;-45&quot; Wide\nDesigner / Author:V and Co. Vanessa Christenson\nGroup Name:Ombre Fairy Dust\nOrigin:Made in Korea\nColor:White\nTheme:Metallics\n\nFabric yardage is sold by the 1/2 yard. Your fabric will be cut in one continuous piece.\n\nIf you want a 1/2 yard, order &quot;1.&quot;\n\nIf you want 1 yard, order &quot;2.&quot;\n\nIf you want 1 1/2 yards, order &quot;3”,\netc\n\nThis item is sold as a continuous cut. \n\nThis item comes from a smoke free home.\n\nI am willing to ship internationally, please contact me for more info",
    "state": "active",
    "creation_timestamp": 1653422069,
    "created_timestamp": 1653422069,
    "ending_timestamp": 1664049269,
    "original_creation_timestamp": 1599851387,
    "last_modified_timestamp": 1653422069,
    "updated_timestamp": 1653422069,
    "state_timestamp": 1653422053,
    "quantity": 2,
    "shop_section_id": 27608025,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/855452154/off-white-ombre-fairy-dust-by-v-and-co",
    "num_favorers": 9,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
    "quilting fabric",
    "moda fabric",
    "ombre metallic",
    "moda ombre",
    "moda ombre metallic",
    "ombre metallic moda",
    "v and co",
    "vanessa christenson",
    "Ombre Fairy Dust",
    "Fairy dust ombre",
    "fairy dust",
    "white"
    ],
    "materials": [
    "moda",
    "cotton",
    "quilting fabric",
    "metallic ombre",
    "Vanessa christenson fairy dust",
    "metallic fairy dust",
    "Fairy Dust",
    "white"
    ],
    "shipping_profile_id": 126758703399,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "someone_else",
    "when_made": "2020_2022",
    "is_supply": true,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": false,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 675,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 562,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 267102805,
    "user_id": 19922112,
    "shop_id": 9048518,
    "title": "Handcrafted Silver Plated Vintage Style Black Jet Crystal Cameo Post Earrings",
    "description": "These antique / vintage style cameo drop earrings give you a real heirloom look and feel.  The cameo cab is set in an antique style frame with black Austrian crystal drop and Victorian style surgical steel posts,  antiqued silver plated, earrings measure 2 inches long. Sent in cotton filled gift box.\n\nAlso available in 24k gold plated metal.",
    "state": "active",
    "creation_timestamp": 1653422068,
    "created_timestamp": 1653422068,
    "ending_timestamp": 1664049268,
    "original_creation_timestamp": 1454778630,
    "last_modified_timestamp": 1653422068,
    "updated_timestamp": 1653422068,
    "state_timestamp": 1636688595,
    "quantity": 1,
    "shop_section_id": 18393040,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/267102805/handcrafted-silver-plated-vintage-style",
    "num_favorers": 9,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
    "Victorian",
    "Vintage",
    "handmade jewelry",
    "black cameo",
    "cameo jewelry",
    "silver earrings",
    "cameo earrings"
    ],
    "materials": [
    "silver plated findings",
    "cameo cab",
    "surgical steel posts"
    ],
    "shipping_profile_id": 32062936998,
    "processing_min": 1,
    "processing_max": 2,
    "who_made": "i_did",
    "when_made": "2010_2019",
    "is_supply": false,
    "item_weight": 3,
    "item_weight_unit": "oz",
    "item_length": 8,
    "item_width": 4,
    "item_height": 1,
    "item_dimensions_unit": "in",
    "is_private": false,
    "style": [
    "Victorian",
    "Renaissance"
    ],
    "file_data": "",
    "has_variations": false,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 2495,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 1208,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 719542105,
    "user_id": 52019674,
    "shop_id": 9868924,
    "title": "Vector WELCOME, cow, heifer, text, ai, eps, pdf, svg, dxf, png, jpg Download, Digital image, graphical, animal farm",
    "description": "Vector WELCOME - INSTANT DOWNLOAD!!!  \n\n═══════════  YOU RECEIVE  ═══════════  \nAfter purchasing this file, you will receive a download link from Etsy. For more help on this you might want to check out the help page Etsy download here: https://www.etsy.com/help/article/3949\n !!! Please make sure you have the proper software to extract / open these files.\n───►   2 vector AI files /one object, just letters are separate/, with and without background;\n───►   1 EPS file no background, /you can open with Adobe Illustrator, Corel Draw/;\n───►   1 PDF file, A4, no background;\n───►   1 SVG file, A4, no background;\n───►   1 DXF file, A4, no background;\n───►   1 PNG file, A4, no background;\n───►   2 JPG files as shown in the listing.\nWatermarks will not appear on the downloaded file.\n\n═══════════  SAVE MONEY  ════════════\nYou can see  coupon codes here:   https://www.etsy.com/shop/DuglyGraphics/policy\n\n═════════  COMMERCIAL USE  ══════════\nYou can see everything about using the file in the shop&#39;s policies: https://www.etsy.com/shop/DuglyGraphics/policy\n\n════════════  SHIPPING  ═════════════\nThis is a digital product so nothing physical will be mailed. So why, NO shipping costs.\n\n══════════  RETURN POLICY  ═══════════\nhttps://www.etsy.com/shop/DuglyGraphics/policy\n\n═════Thank you for visiting my shop! ══════ ♥",
    "state": "active",
    "creation_timestamp": 1653422068,
    "created_timestamp": 1653422068,
    "ending_timestamp": 1664049268,
    "original_creation_timestamp": 1562505507,
    "last_modified_timestamp": 1653422068,
    "updated_timestamp": 1653422068,
    "state_timestamp": 1642283911,
    "quantity": 816,
    "shop_section_id": 15893441,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/719542105/vector-welcome-cow-heifer-text-ai-eps",
    "num_favorers": 278,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "download",
    "tags": [
    "feathered pet art",
    "poultry cow farm",
    "interior art design",
    "wall home decoration",
    "funny print decor",
    "cut cameo mashine",
    "welcome text file",
    "cute pdf png heifer",
    "printable animals",
    "domestic drawing",
    "digital dxf eps ai",
    "fun prints for frame",
    "draw sign ideas"
    ],
    "materials": [],
    "shipping_profile_id": null,
    "processing_min": null,
    "processing_max": null,
    "who_made": "i_did",
    "when_made": "2020_2022",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [
    "Vector"
    ],
    "file_data": "1 ZIP, 1 other file",
    "has_variations": false,
    "should_auto_renew": false,
    "language": "en-US",
    "price": {
    "amount": 250,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 77,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 1173460917,
    "user_id": 8131507,
    "shop_id": 5662677,
    "title": "Tigers Softball Digital Design / Distressed Ripped Softball / Game Day Game On / Sublimation PNG File Digital Download / Instant Download",
    "description": "This listing is for one digital image to use for both personal and commercial purposes, such as t-shirts, stationary, cards, flyers, decals etc. This image is perfect for sublimation printing. \n\nThe file will automatically download once purchased.\nYou will receive a file free from watermarking/shop logos.\n*You will not receive a physical product.* \nThis is NOT a SVG file for cutting. \n\nAll files are in PNG format unless otherwise noted. \nYou may request another format if desired. \nPlease contact me with any questions!",
    "state": "active",
    "creation_timestamp": 1653422067,
    "created_timestamp": 1653422067,
    "ending_timestamp": 1664049267,
    "original_creation_timestamp": 1644031083,
    "last_modified_timestamp": 1653422067,
    "updated_timestamp": 1653422067,
    "state_timestamp": 1653422029,
    "quantity": 1,
    "shop_section_id": 30730559,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/1173460917/tigers-softball-digital-design",
    "num_favorers": 21,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "download",
    "tags": [
    "game day",
    "sublimation",
    "bleached",
    "digital download",
    "it's game day",
    "opening day",
    "softball png",
    "game day png",
    "softball marquee",
    "distressed softball",
    "baseball png",
    "marquee letter png",
    "tigers png"
    ],
    "materials": [
    "sublimation",
    "digital download",
    "marquee letter",
    "softball"
    ],
    "shipping_profile_id": null,
    "processing_min": null,
    "processing_max": null,
    "who_made": "i_did",
    "when_made": "2020_2022",
    "is_supply": true,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "1 PNG",
    "has_variations": false,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 500,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 2078,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 1202023360,
    "user_id": 22610249,
    "shop_id": 7008675,
    "title": "Christmas - Holiday - Rudolph - Nail Wrap - Nail Strip -  Dry Nail Polish",
    "description": "Christmas - Holiday - Rudolph - Nail Wrap - Nail Strip -  Dry Nail Polish\n\nHow to use:\n\nStep 1: Clean and dry your nails\n\nStep 2: Select the right fit\n\nStep 3: Remove the clear protective cover and peel the wrap from the backing\n\nStep 4: Line the wrap up right to the edge of your cuticle and rub firmly to adhere. Be careful not to place it on your skin, as it will affect the length of wear.\n\nStep 5: File off the excess in a downward motion\n\nOptional (but recommended) Step 6: apply a top coat for extra durability. Do not use “quick dry” top coats as they will cause the wrap to wrinkle/shrink.\n\nOther tips:\nAvoid lotion, submerging hands in water or other wet or messy activities for a couple of hours to allow the wraps to set. I find it best to put them on before bed, and then wake up and put a top coat on.\n\nIf you’re seeing bubbles or wrinkles on the second day, you may not have pressed or rubbed firmly enough when applying.\n\nIt’s better to size down than up - using a wrap too big for your nails will prevent a good seal from forming if the wrap is touching your skin.",
    "state": "active",
    "creation_timestamp": 1653422066,
    "created_timestamp": 1653422066,
    "ending_timestamp": 1664049266,
    "original_creation_timestamp": 1650035415,
    "last_modified_timestamp": 1653422066,
    "updated_timestamp": 1653422066,
    "state_timestamp": 1653421238,
    "quantity": 4,
    "shop_section_id": null,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/1202023360/christmas-holiday-rudolph-nail-wrap-nail",
    "num_favorers": 1,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
    "black and white",
    "dry nail polish",
    "nail wrap",
    "nail sticker",
    "nail polish",
    "nail strips",
    "nail polish wrap",
    "nail stickers",
    "nail strip",
    "christmas",
    "reindeer",
    "rudolph",
    "holidays"
    ],
    "materials": [
    "Nail polish",
    "nontoxic adhesive"
    ],
    "shipping_profile_id": 155882480,
    "processing_min": 1,
    "processing_max": 2,
    "who_made": "someone_else",
    "when_made": "2020_2022",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": false,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 500,
    "divisor": 100,
    "currency_code": "CAD"
    },
    "taxonomy_id": 1992,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 888943093,
    "user_id": 320629592,
    "shop_id": 23779840,
    "title": "Snow Flakes on Red color real nail polish wraps ZZ102 street art strips",
    "description": "Snow Flakes on Red ZZ102\n\nReal nail polish strips.  Easy to apply, goes on dry.  Perfect manicure in 15 minutes.  No smudging or peeling.  No tools or curing equipment necessary.  Lasts 10 days or more.  Easy to remove with nail polish remover.  Each pack includes 16 strips.",
    "state": "active",
    "creation_timestamp": 1653422066,
    "created_timestamp": 1653422066,
    "ending_timestamp": 1664049266,
    "original_creation_timestamp": 1603036122,
    "last_modified_timestamp": 1653422066,
    "updated_timestamp": 1653422066,
    "state_timestamp": 1653421237,
    "quantity": 59,
    "shop_section_id": 34701216,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/888943093/snow-flakes-on-red-color-real-nail",
    "num_favorers": 62,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
    "white red",
    "snow flakes",
    "christmas holidays",
    "winter fall",
    "autumn fun",
    "color street",
    "wrap wraps",
    "strip strips",
    "sticker stickers",
    "gift gifts",
    "party parties",
    "free shipping",
    "nail polish"
    ],
    "materials": [
    "nail polish"
    ],
    "shipping_profile_id": 147765260668,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "someone_else",
    "when_made": "2020_2022",
    "is_supply": false,
    "item_weight": 0.25,
    "item_weight_unit": "oz",
    "item_length": 9,
    "item_width": 6,
    "item_height": 0.25,
    "item_dimensions_unit": "in",
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": false,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 400,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 1994,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 1142978322,
    "user_id": 18189718,
    "shop_id": 6700417,
    "title": "On Point Ombre nail polish wraps, nail polish stickers, nail strips, nail decals, nail art, chevron nail, nail polish strips, nail wrap 1607",
    "description": "Nail wrap or decals.  Nail wraps are changing the manicure process.  A cheaper process that allows you to apply at home.\n- Simply peel the nail polish strips and apply to a clean nail bed.\n- File away the excess for an instant manicure.\n- Intended to fit adult nails, however they can be stretched and trimmed.\n- Non-toxic, made of 100% nail polish.  They do have an adhesive backing to help adhere to the nail bed.\nThis listing includes 1 nail wrap, as pictured, each order will include a cuticle stick, alcohol swab, instruction card, and nail file.  If additional instruction card is needed, please message me to include with order.\n\nTips for best application:\n- Lightly buff the nail bed with the nail file to reduce ridges in the nail bed.  This helps with adherence of the nail wrap as well.\n- Use a ph bond or Orly bonder prior to adhering to the nail bed, this will dry out the nail bed removing any oils that may be on the nail bed.\n- Use the alcohol swab included to clean nail beds and fingertips to ensure clean nail bed area.\n- After applying refrain from soaking hands in water for 8 hours.\n- It is best to apply prior to bed to allow time for nail wraps to set.\n- If you have shorter nails, one wrap will can give you 2 manicures.  If you use one side for one manicure by cutting the excess off each nail and then applying that excess to the other hand.",
    "state": "active",
    "creation_timestamp": 1653422065,
    "created_timestamp": 1653422065,
    "ending_timestamp": 1664049265,
    "original_creation_timestamp": 1641748699,
    "last_modified_timestamp": 1653422065,
    "updated_timestamp": 1653422065,
    "state_timestamp": 1653421238,
    "quantity": 16,
    "shop_section_id": 36743009,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/1142978322/on-point-ombre-nail-polish-wraps-nail",
    "num_favorers": 4,
    "non_taxable": true,
    "is_taxable": false,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
    "nail decals",
    "nails",
    "fingernails",
    "nail wraps",
    "nail wrap",
    "glitter nail",
    "chevron nail",
    "nail polish wraps",
    "nail polish stickers",
    "nail stickers",
    "nail polish strips",
    "purple nails",
    "gifts for her"
    ],
    "materials": [
    "nail polish"
    ],
    "shipping_profile_id": 173502823826,
    "processing_min": 5,
    "processing_max": 7,
    "who_made": "i_did",
    "when_made": "2020_2022",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": false,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 350,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 1994,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 890903892,
    "user_id": 344315455,
    "shop_id": 24441578,
    "title": "Santa Sparkle Print Nailwraps - Nail Polish Strips",
    "description": "These nail wraps are the perfect touch to your winter ensemble. The pattern features a mix of Santas, glittery gifts and snowflakes. Such a fun combination! The application is easy and apply flawlessly to your nails! \n\nPro tip: file your nails thoroughly to provide good grip for the wraps or apply a rubberized base coat polish to maximize adhesion. The wraps can last up to 10 days with proper preparation! \n\nAs a bonus, for shorter nails, each wrap can be cut in half so there is no waste of the pretty design! \n\nEach wrap is made of thin, 100% nail polish and can be mixed and matched to any other colors or patterns you’d like! I’ve used these for years and can attest these are the best on the market. I love the ease of application and how perfect they look when applied. (Not to mention fast!) Get ready to be asked where you get your nails done! \n\nSome pro tips for application:\n- make sure your nails are clean and dry; no oils or lotions should be present. Use a quick swipe of alcohol or nail polish remover to remove any build up\n- I’ve had better luck slightly buffing the top of my nail with a fine grade nail board. This isn’t necessary, but it gives the wrap a bit more grip to hold on to. \n- most wraps will probably have to be trimmed to fit your nail perfectly. The key is getting it slightly smaller than your actual nail size with no skin or cuticle overlap. I trim the overhang with scissors then file the rest off.\n- make sure to seal the top with a clear polish if you want them to last a long time. \n\nA list of instructions and a nail file will be included with each order. \n\nYou got this! Enjoy!",
    "state": "active",
    "creation_timestamp": 1653422065,
    "created_timestamp": 1653422065,
    "ending_timestamp": 1664049265,
    "original_creation_timestamp": 1605414015,
    "last_modified_timestamp": 1653422065,
    "updated_timestamp": 1653422065,
    "state_timestamp": 1653421237,
    "quantity": 29,
    "shop_section_id": 30208844,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/890903892/santa-sparkle-print-nailwraps-nail",
    "num_favorers": 139,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
    "winter nail art",
    "winter nail wraps",
    "Christmas nail art",
    "Thanksgiving nail wr",
    "nailwraps",
    "nail polish strips",
    "color street wrap",
    "Nail wraps",
    "nail polish wraps",
    "easy manicure",
    "DIY manicure",
    "metallic manicure",
    "nail stickers"
    ],
    "materials": [
    "Nail polish wraps"
    ],
    "shipping_profile_id": 116269172439,
    "processing_min": 1,
    "processing_max": 2,
    "who_made": "someone_else",
    "when_made": "2020_2022",
    "is_supply": false,
    "item_weight": 4,
    "item_weight_unit": "oz",
    "item_length": 9,
    "item_width": 6,
    "item_height": 1,
    "item_dimensions_unit": "in",
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": false,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 399,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 1994,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 475417879,
    "user_id": 11327831,
    "shop_id": 6065043,
    "title": "WOODLAND Animals Wall Art Forest Animals Woodland Nursery Decor Beige Birch Tree Wood Fox Squirrel Moose Raccoon",
    "description": "WOODLAND Animals Wall Art Forest Animals Woodland Nursery Decor Beige Birch Tree Wood Fox Squirrel Moose Raccoon\n\nChoose CANVAS or Print option.\n\nThis lovely wall art of four prints features the cutest woodland animal illustrations and will bring whimsy and wonder in any baby space.\nYou may choose any 4 from the 9 animals shown in Photo 2. Just leave me a note at check out.\n\n• 4 PAPER PRINTS or CANVAS WRAPS - choose size from the Selections menu\n\n▶ ARTWORK SIZE OPTIONS - SEE DETAILED DESCRIPTION IN LISTING PHOTOS\n\n▶ PAPER PRINT\n• Printed on Luster photo paper\n• Custom sizes available per request\n\nIf you need a specific size, not listed, just send us a message.\n\n▶ CANVAS WRAP - Arrive ready to hang!\n• 1.25&quot; deep\n• Genuine artist canvas using UV resistant archival inks.\n\nColors, Backgrounds & Quotes can be CUSTOMIZED!\nLeave us a message in the &quot;Note to Seller&quot; box at check out. \n\n▶ COLOR CHART - click on the link here: http://bit.ly/2ENjJzl\n\nBUY OUR COLOR CHART here - https://www.etsy.com/listing/150652372/\n\n▶ Colors on screens may appear different in print due to variations in monitor settings.\nIf you do not specify colors, your order will be printed with the colors in the first example image of the listing. \n\n© YassisPlace All rights reserved",
    "state": "active",
    "creation_timestamp": 1653422064,
    "created_timestamp": 1653422064,
    "ending_timestamp": 1664049264,
    "original_creation_timestamp": 1472501327,
    "last_modified_timestamp": 1653422064,
    "updated_timestamp": 1653422064,
    "state_timestamp": 1653157154,
    "quantity": 1,
    "shop_section_id": 26317753,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/475417879/woodland-animals-wall-art-forest-animals",
    "num_favorers": 663,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": true,
    "is_personalizable": true,
    "personalization_is_required": false,
    "personalization_char_count_max": 1024,
    "personalization_instructions": "Customizations:\n-Color changes - review the color chart and type your colors\n-Proofs sent upon request\n-If no changes are needed, please type- As Pictured",
    "listing_type": "physical",
    "tags": [
    "Woodland wall art",
    "Woodland Theme",
    "Moose Raccoon Fox",
    "Woodland Nursery Art",
    "Woodland Animal Art",
    "Wood Forest Animals",
    "Woodland Birch Tree",
    "Woodland Decor",
    "Nursery Decor",
    "Woodland Animals",
    "Wall Art",
    "Woodland Art Prints",
    "Woodland Nursery"
    ],
    "materials": [
    "Luster Photo Paper Prints",
    "or Canvas Wrap 1 point 25 inches deep",
    "Choose size and material in selection menu",
    "Please read the DESCRIPTION for detailed info",
    "Custom colors and sizes available",
    "Use coupon code DIGITAL for",
    "free shipping on digital  purchases"
    ],
    "shipping_profile_id": 53102786704,
    "processing_min": 1,
    "processing_max": 10,
    "who_made": "i_did",
    "when_made": "made_to_order",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": true,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 2000,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 2078,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 707263829,
    "user_id": 24725190,
    "shop_id": 7276209,
    "title": "St. Winifred Fine Art Print, Catholic Patron Saint against unwanted advances",
    "description": "Saint Winifred Fine Art Print\n\nChoose 8x10”, 11x14”, 16x20”, 18x24” 20x26”, or 22x28&quot; print size. \n\nDESCRIPTION:\nThis fine art print is ready to frame. It is a copy of my original Prismacolor pencil portrait. The 8x10&quot; and 11x14&quot; are printed on acid-free 80 lb. cardstock. The 16x20&quot; and larger are printed on premium 11-mil, acid-free paper. The watermark will not appear on your print.\n\nPACKAGING:\n8 x 10&quot; images are printed on 8.5 x 11&quot; paper. All prints 11x14 and larger are carefully rolled and shipped in a rigid mailing tube to ensure safe shipment. We take great care to package your order so it arrives in perfect condition.\nOrder with confidence!\n\nSHIPPING:\nThis item SHIPS FREE anywhere in the USA!\n\nADDITIONAL INFO:\nSaint Winifred\n600-660\nFeast Day: November 3\nPatronage: Virgins, from unwanted advances, incest victims, martyrs, Holywell, Wales, Gwytherin, Wales, Shrewsbury, England\n\nSaint Winifred was from a wealthy Welsh family. Legend has it that she was beheaded by a rejected suitor, Prince Caradog. Winifred’s uncle, Saint Beuno, miraculously restored her head and life. A spring sprung up where her head fell called Holywell or St. Winifred’s Well (the Lourdes of Wales) where pilgrims travel to and many miracles take place. Winifred later became a nun and Abbess at Gwytherin in Wales.\n\n©Tracy L. Christianson, all rights reserved.",
    "state": "active",
    "creation_timestamp": 1653422064,
    "created_timestamp": 1653422064,
    "ending_timestamp": 1664049264,
    "original_creation_timestamp": 1558187216,
    "last_modified_timestamp": 1653422064,
    "updated_timestamp": 1653422064,
    "state_timestamp": 1608577846,
    "quantity": 11,
    "shop_section_id": 12165091,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/707263829/st-winifred-fine-art-print-catholic",
    "num_favorers": 16,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
    "Catholic gifts",
    "Baptism gift",
    "Free Shipping",
    "Religious art",
    "Catholic",
    "Religious gifts",
    "Fine art",
    "teamcatholic",
    "patron saint",
    "ecatholicteam",
    "unwanted advances",
    "martyrs",
    "virgins"
    ],
    "materials": [],
    "shipping_profile_id": 4480396555,
    "processing_min": 1,
    "processing_max": 4,
    "who_made": "i_did",
    "when_made": "2010_2019",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": true,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 1400,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 119,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 868673889,
    "user_id": 53767973,
    "shop_id": 10047537,
    "title": "Leather Oversized Coat Vintage 80&#39;s Real Genuine Leather Coat Women&#39;s Brown Leather Parka With Shoulder Pads Leather TrenchCoat Medium Size",
    "description": "Women&#39;s Brown Leather Coat Express Ladies&#39; Brown Leather Jacket Motorcycle Bomber Jacket Womens Leather Trench Coat Blazer Medium Size. This nice jacket is in good condition.  Nicely lined. \nLabel size: 40\nMaterial - 100% real leather\nLining - 100% polyester\n\nLength (back): 31.4&quot;/ 80 cm\nBust : 22&quot;/ 56 cm\nWaist: 22&quot;/56 cm\nSleeve: 20&quot;/51 cm\nShoulder: 23&quot;/58 cm\n\nPlease check measurements to insure a proper fit. Remember to allow yourself some extra room for movement. You can compare these with something from your closet that fits you well.\n\n\n\nSHIPPING\n* I ship worldwide via Priority mail (Latvijas Pasts) from Latvia (EU).\n* I ship from Europe, so please allow 2 to 4 weeks for the package to arrive if you live overseas.\n* Europe 5 - 10 business days.\n\n\nc.123",
    "state": "active",
    "creation_timestamp": 1653422062,
    "created_timestamp": 1653422062,
    "ending_timestamp": 1664049262,
    "original_creation_timestamp": 1599745384,
    "last_modified_timestamp": 1653422063,
    "updated_timestamp": 1653422063,
    "state_timestamp": 1653152419,
    "quantity": 1,
    "shop_section_id": 16860418,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/868673889/leather-oversized-coat-vintage-80s-real",
    "num_favorers": 10,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
    "Long leather blazer",
    "Brown leather jacket",
    "Brown leather coat",
    "Vintage 80s",
    "bomber jacket",
    "hipster coat",
    "brown leather parka",
    "long leather jacket",
    "Leather Parka Coat",
    "real leather coat",
    "oversized jacket",
    "genuine leather",
    "Oversized Coat"
    ],
    "materials": [
    "Leather",
    "Vintage Leather"
    ],
    "shipping_profile_id": 107815525482,
    "processing_min": 3,
    "processing_max": 5,
    "who_made": "someone_else",
    "when_made": "1980s",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": false,
    "should_auto_renew": false,
    "language": "en-US",
    "price": {
    "amount": 4400,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 507,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 1238526749,
    "user_id": 71635592,
    "shop_id": 11988520,
    "title": "Union Jack Flag 5 x 3ft Fade Resistant Polyester, Metal Eyelets, Double Stitched Perfect for Jubilee & British Celebrations Fast Free Post",
    "description": "Large Union Jack Flag, ideal for any home or event including The Platinum Jubilee and all Traditional, Royal, Military and British Themes.\n\n5 x 3 ft Polyester \n\nDouble stitched\n\nFast Free Post \n\nDesign includes hoisting holes\n\nExcellent Quality!",
    "state": "active",
    "creation_timestamp": 1653422060,
    "created_timestamp": 1653422060,
    "ending_timestamp": 1664049260,
    "original_creation_timestamp": 1653338264,
    "last_modified_timestamp": 1653422060,
    "updated_timestamp": 1653422060,
    "state_timestamp": 1653338264,
    "quantity": 39,
    "shop_section_id": 38313018,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/1238526749/union-jack-flag-5-x-3ft-fade-resistant",
    "num_favorers": 0,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
    "Union Flag",
    "Union Jack Flag",
    "Union Jack",
    "Red",
    "White",
    "Blue",
    "British",
    "Military",
    "Jubilee",
    "Royals",
    "Red white and blue",
    "Decorate",
    "Patriotic"
    ],
    "materials": [],
    "shipping_profile_id": 158081867926,
    "processing_min": 1,
    "processing_max": 1,
    "who_made": "someone_else",
    "when_made": "2020_2022",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": false,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 600,
    "divisor": 100,
    "currency_code": "GBP"
    },
    "taxonomy_id": 1339,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 1239119517,
    "user_id": 21066002,
    "shop_id": 6854275,
    "title": "Caspian Concho - Antique Silver Plate - 3 sizes available",
    "description": "Caspian Concho\n- Antique Silver Plate\n- 3 sizes available: 1/2&quot;, 3/4&quot;, 1&quot;\n- Has a screw-back attachment",
    "state": "active",
    "creation_timestamp": 1653422060,
    "created_timestamp": 1653422060,
    "ending_timestamp": 1664049260,
    "original_creation_timestamp": 1653422060,
    "last_modified_timestamp": 1653422062,
    "updated_timestamp": 1653422062,
    "state_timestamp": 1653422060,
    "quantity": 30,
    "shop_section_id": 22916674,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/1239119517/caspian-concho-antique-silver-plate-3",
    "num_favorers": 0,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
    "concho",
    "Copper",
    "Caspian concho",
    "Antique",
    "Antique silver plate",
    "antique silver",
    "silver"
    ],
    "materials": [
    "silver",
    "antique silver"
    ],
    "shipping_profile_id": 45940181149,
    "processing_min": 1,
    "processing_max": 2,
    "who_made": "someone_else",
    "when_made": "2020_2022",
    "is_supply": false,
    "item_weight": 2,
    "item_weight_unit": "oz",
    "item_length": 9,
    "item_width": 6,
    "item_height": 1,
    "item_dimensions_unit": "in",
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": true,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 400,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 6353,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 763204776,
    "user_id": 37508259,
    "shop_id": 22304092,
    "title": "Intuition Soy Crystal Candle",
    "description": "Our Intuition Candle is made from soy wax, egyptian amber oil, mugwort, yarrow, blue cornflower and infused with amethyst\nEnhance your intuition and connect to spirit guides. Perfect to use during meditation and when working on psychic abilities.",
    "state": "active",
    "creation_timestamp": 1653422060,
    "created_timestamp": 1653422060,
    "ending_timestamp": 1664049260,
    "original_creation_timestamp": 1581142992,
    "last_modified_timestamp": 1653422060,
    "updated_timestamp": 1653422060,
    "state_timestamp": 1643038823,
    "quantity": 2,
    "shop_section_id": 30399480,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/763204776/intuition-soy-crystal-candle",
    "num_favorers": 70,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
    "Crystal candle",
    "ritual candle",
    "intention candle",
    "intuition candle",
    "spell candle",
    "magic candle",
    "amethyst candle"
    ],
    "materials": [
    "Soy"
    ],
    "shipping_profile_id": 86162615589,
    "processing_min": 3,
    "processing_max": 5,
    "who_made": "i_did",
    "when_made": "2020_2022",
    "is_supply": false,
    "item_weight": 20,
    "item_weight_unit": "oz",
    "item_length": 4,
    "item_width": 3,
    "item_height": 4,
    "item_dimensions_unit": "in",
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": false,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 2500,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 1005,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 1110003437,
    "user_id": 7796608,
    "shop_id": 26559370,
    "title": "Fairy Jar PRINTABLE ART, Girls Room Decor, Fairies Printable, Girls Fairy Nursery Print Girls Room Art, Poster Art girl, Whimsical Girl Art",
    "description": "Whimsical Fairies for girls bedroom or nursery.\n\nThis is a DIGITAL DOWNLOAD ONLY. \nNO  physical product will be sent.\n\nYou will receive Five Sizes for each artwork, US Sizes 5x7, 8x10, 11x14, 16x20 and International Size A3 (this can also be resized to A4, A5 and A6)\nIf you should need a different size please just message me to let me know.\n\nThis is for PERSONAL USE ONLY. You may print for yourself or to give as a gift. \nDo not share, alter or sell.\nThis is not for commercial use.\n\nWhat happens after I purchase?\n\nAfter your payment has been confirmed, Etsy will send you a email for a link to download.\nJust download files to your computer. Sizes are listed on file names for example &quot;Bear 8x10 jpg&quot;\nIf you are ordering a set with 2 or more artworks, your files will come in a zipped folder. Just right click and extract. You will be able to print from your home computer, or places that offer printing like, Staples, Kinkos, Costco or your favorite local printers.\nThen just place in a frame and hang. It’s that easy. \n\nKeep in mind, colors can look slightly different from computers and printers.\n**Images are shown is various mock up frames. This is just to give you an idea of what it could look like in a room. Many have been resized to fit the mock up frames. \n\nAll Commercial Licenses have been purchased to create artwork.\n\nThank You so much for stopping by, reach out to me with any questions.",
    "state": "active",
    "creation_timestamp": 1653422060,
    "created_timestamp": 1653422060,
    "ending_timestamp": 1664049260,
    "original_creation_timestamp": 1635390594,
    "last_modified_timestamp": 1653422060,
    "updated_timestamp": 1653422060,
    "state_timestamp": 1635397391,
    "quantity": 499,
    "shop_section_id": 31735353,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/1110003437/fairy-jar-printable-art-girls-room-decor",
    "num_favorers": 7,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "download",
    "tags": [
    "PRINTABLE WALL ART",
    "girls room decor",
    "fairies printable",
    "nursery print",
    "digital download",
    "nursery wall art",
    "Girls wall art",
    "Fairy Playroom",
    "whimsical fairy",
    "girl fairy",
    "birthday fairy gift",
    "whimsical girl print",
    "fairy jar print"
    ],
    "materials": [],
    "shipping_profile_id": null,
    "processing_min": null,
    "processing_max": null,
    "who_made": "i_did",
    "when_made": "2020_2022",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "5 JPG",
    "has_variations": false,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 575,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 2078,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 1009308346,
    "user_id": 228961492,
    "shop_id": 20716465,
    "title": "Gents Sign, Men Bathroom Over The Toilet Restroom Metal Sign, Distressed Custom Metal Sign, Rustic Street Sign or Door Name Plate Plaque",
    "description": "Design: Gents Bathroom Rustic Custom Sign\n\nPlease note, all rustic add-ons including any rust, distressed marks, etc. are printed on and not real, so the signs are smooth to the touch.\n\n• We have multiple sizes available. To see our current sizes available, click the drop down menu for each style.\n\nPLEASE REMEMBER: We highly recommend taking tape and measuring the spot you plan on placing the sign at to ensure you order the right size for your perfect spot! All signs are made to order custom just for you!\n\n• Background Color: Choose from Distressed White (with main text being black as shown in example) or Distressed Asphalt (with main text being white as shown in example). Examples of both are in the photo slide show.\n\n***METAL SIGN FEATURES***\n\n• Aluminum Metal Sign With Rounded Corners\n\n• Indoor or Outdoor Use\n\n• Two Hanging Options:\n\n1. Ready To Hang – Two Pre-Drilled Holes Centered On The Shortest Sides Of The Sign As Shown In The Photo Slide Above (No Hardware Is Included). These holes can NOT be moved to a different location.\n\n2. No Holes – Command Strips Are Popular For Hanging Versus Nails\n\n• Thickness: 0.032 Inches - Perfect for thin light-weight art on the wall! There is a picture in the slide show that shows the thickness as well.\n\n• Gloss Print - Increased Vibrancy Of Artwork\n\n• All metal signs ship in 1 to 3 business days. \n\n\n\n• Colors can vary a bit on different monitors and screens. Any props included in photos are not included.\n\nNOTE: The main picture is of a 3&quot; x 12&quot; metal sign.",
    "state": "active",
    "creation_timestamp": 1653422060,
    "created_timestamp": 1653422060,
    "ending_timestamp": 1664049260,
    "original_creation_timestamp": 1621619389,
    "last_modified_timestamp": 1653422060,
    "updated_timestamp": 1653422060,
    "state_timestamp": 1653421245,
    "quantity": 999,
    "shop_section_id": 28551597,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/1009308346/gents-sign-men-bathroom-over-the-toilet",
    "num_favorers": 1,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": true,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
    "Custom Family Name",
    "weathered wood sign",
    "monogram grunge sign",
    "black farmhouse home",
    "vintage novelty gift",
    "Street Sign Plaque",
    "Door Name Plate",
    "pool house sign",
    "Shower Bathroom sign",
    "rustic distressed",
    "restroom pub bar",
    "Men bathroom sign",
    "Gents bathroom sign"
    ],
    "materials": [
    "Metal",
    "Aluminum"
    ],
    "shipping_profile_id": 98857102273,
    "processing_min": 1,
    "processing_max": 3,
    "who_made": "i_did",
    "when_made": "made_to_order",
    "is_supply": false,
    "item_weight": 7.9,
    "item_weight_unit": "oz",
    "item_length": 12,
    "item_width": 9,
    "item_height": 0.5,
    "item_dimensions_unit": "in",
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": true,
    "should_auto_renew": false,
    "language": "en-US",
    "price": {
    "amount": 2199,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 2844,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 1239119509,
    "user_id": 630290037,
    "shop_id": 35860604,
    "title": "Botanical I Frame Wrapped Canvas",
    "description": "Let your personality be reflected on the artwork adorning your walls. This vertical gallery wrapped canvas print will always look as tight and flat as the day it was made. Every frame is built with a solid face to support the canvas and prevent deforming. Available in multiple sizes, comes in walnut and black frame options.\n.: 100% cotton fabric canvas\n.: Poplar wood frame with walnut or black finish\n.: High image quality and detail\n.: NB! For indoor use only",
    "state": "active",
    "creation_timestamp": 1653422059,
    "created_timestamp": 1653422059,
    "ending_timestamp": 1664049259,
    "original_creation_timestamp": 1653422059,
    "last_modified_timestamp": 1653422063,
    "updated_timestamp": 1653422063,
    "state_timestamp": 1653422059,
    "quantity": 1998,
    "shop_section_id": null,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/1239119509/botanical-i-frame-wrapped-canvas",
    "num_favorers": 0,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [],
    "materials": [],
    "shipping_profile_id": 174596359439,
    "processing_min": 1,
    "processing_max": 7,
    "who_made": "i_did",
    "when_made": "made_to_order",
    "is_supply": false,
    "item_weight": null,
    "item_weight_unit": null,
    "item_length": null,
    "item_width": null,
    "item_height": null,
    "item_dimensions_unit": null,
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": true,
    "should_auto_renew": false,
    "language": "en-US",
    "price": {
    "amount": 4455,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 6464,
    "production_partners": [],
    "skus": []
    },
    {
    "listing_id": 1236153389,
    "user_id": 107778797,
    "shop_id": 14614581,
    "title": "Grow Your Own Way Baby Bib or Burping Cloth - Mushroom Retro Boho Feeding Bib",
    "description": "Handmade by Wandering Cosmic Hearts. Design is printed using a direct to garment printer. Backside is blank. GROW YOUR OWN WAY Baby Bib. \n\nPrinted on a cotton blend knit terry. 75% cotton, 25% polyester. Recommended for ages 3-9 months. Machine washable and dryer safe. \n\nThis design is DTG printed, this is NOT sublimation, iron on or vinyl, it is high quality direct to garment printed which means you can wash and dry as often as needed and you never have to worry about the image design fading. Beautiful, vibrant print. \n\nCOFFEE DYED COLORS -. All the coffee colors are hand-dyed by me right here at the studio. Available colors are WINTER WHITE, LIGHT COFFEE, MEDIUM COFFEE and DARK ROAST. The light coffee color is the off-white natural looking color that you see in a lot of the product photos. The coffee colors are lightly hand washed in a free and clear laundry soap and rinsed thoroughly. The end result leaves a beautiful flawless color. \n\nREFUNDS and CANCELLATIONS: Bib printing is made to order, once the bib has been colored and/or printed, I will not be able to cancel or refund. If you made a mistake with sizing or something else, please message me as soon as you can or immediately after to make a change or to cancel. Because these bibs are made to order, I am unable to offer refunds or exchanges. Each bib is quality inspected during packaging. \n\nSHIPPING: Shipping time frame is 2-3 days after order is placed, sometimes sooner. Most bib orders are shipped USPS First Class. If your order is over $35, then you qualify for free first-class shipping. USPS Priority is used for multiple items with a combined weight over 15 ounces. If you need your order rushed or need it for a baby shower or other event, please kindly message me and I will do my very best to get your order shipped out ASAP. \n\nCUSTOM or PERSONALIZATION: I do offer custom and personalized bibs. I can do rock bands, birth or baby announcement shirts, special images or clipart, characters and more. Whatever design you would like, just reach out to me and I will do my best to put something fabulous together for you. You will receive mockup images until you are happy with your design that you choose. \n\nPlease be sure to include a gift message if the item is being sent to a loved one, family or friend. If the gift message box is left blank, then the gift recipient will not know who it is from. Please also make sure you have the correct shipping address when checking out.\n\nThank you so much for checking out my shop and I look forward to creating a shirt for your little one to wear proudly.\n\nMany Blessings,\n- Danielle @ WCH",
    "state": "active",
    "creation_timestamp": 1653422059,
    "created_timestamp": 1653422059,
    "ending_timestamp": 1664049259,
    "original_creation_timestamp": 1652984782,
    "last_modified_timestamp": 1653422059,
    "updated_timestamp": 1653422059,
    "state_timestamp": 1652984782,
    "quantity": 998,
    "shop_section_id": 38284154,
    "featured_rank": -1,
    "url": "https://www.etsy.com/listing/1236153389/grow-your-own-way-baby-bib-or-burping",
    "num_favorers": 0,
    "non_taxable": false,
    "is_taxable": true,
    "is_customizable": false,
    "is_personalizable": false,
    "personalization_is_required": false,
    "personalization_char_count_max": null,
    "personalization_instructions": null,
    "listing_type": "physical",
    "tags": [
    "baby shower gift",
    "baby bib",
    "food bib",
    "burp cloth",
    "burping cloth",
    "baby gift",
    "hippie bib",
    "mushroom bib",
    "retro baby gift",
    "retro baby bib"
    ],
    "materials": [],
    "shipping_profile_id": 164083310123,
    "processing_min": 3,
    "processing_max": 5,
    "who_made": "i_did",
    "when_made": "made_to_order",
    "is_supply": false,
    "item_weight": 3,
    "item_weight_unit": "oz",
    "item_length": 9,
    "item_width": 1,
    "item_height": 6,
    "item_dimensions_unit": "in",
    "is_private": false,
    "style": [],
    "file_data": "",
    "has_variations": true,
    "should_auto_renew": true,
    "language": "en-US",
    "price": {
    "amount": 599,
    "divisor": 100,
    "currency_code": "USD"
    },
    "taxonomy_id": 2087,
    "production_partners": [],
    "skus": []
    }
    ]
    }